# Generated by Django 2.2.9 on 2020-02-04 02:30

import bookshelf.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='uploadcsv',
            name='file',
            field=models.FileField(upload_to='media/', validators=[bookshelf.validators.validate_extension_csv]),
        ),
    ]
